import * as THREE from "three";

/**
 * Generated by img2blockbench from its Minecraft cuboid scene spec.
 * Edit the JSON specification, not this generated file.
 */
export function createCoinpileSmallModel(): THREE.Group {
  const root = new THREE.Group();
  root.name = "coinpile_small";
  const materials = [
    new THREE.MeshBasicMaterial({ name: "coin_gold", color: "#c1702a", toneMapped: false }),
    new THREE.MeshBasicMaterial({ name: "coin_rim", color: "#fbab15", toneMapped: false }),
    new THREE.MeshBasicMaterial({ name: "coin_shadow", color: "#a3502e", toneMapped: false }),
  ];

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 1, 3),
      [materials[0], materials[0], materials[1], materials[0], materials[2], materials[0]],
    );
    mesh.name = "coin_back_left";
    mesh.position.set(-5.5, 0.5, -1.5);
    const pivot = new THREE.Group();
    pivot.name = "coin_back_left_pivot";
    pivot.position.set(0, 0, 0);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 1, 3),
      [materials[0], materials[0], materials[1], materials[0], materials[2], materials[0]],
    );
    mesh.name = "coin_back_mid";
    mesh.position.set(-2.5, 0.5, -1.5);
    const pivot = new THREE.Group();
    pivot.name = "coin_back_mid_pivot";
    pivot.position.set(0, 0, 0);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 1, 3),
      [materials[0], materials[0], materials[1], materials[0], materials[0], materials[0]],
    );
    mesh.name = "coin_back_right";
    mesh.position.set(0.5, 0.5, -1.5);
    const pivot = new THREE.Group();
    pivot.name = "coin_back_right_pivot";
    pivot.position.set(0, 0, 0);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(4, 1, 3),
      [materials[0], materials[0], materials[1], materials[0], materials[0], materials[2]],
    );
    mesh.name = "coin_front_left";
    mesh.position.set(-5, 0.5, 2.5);
    const pivot = new THREE.Group();
    pivot.name = "coin_front_left_pivot";
    pivot.position.set(0, 0, 0);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 1, 3),
      [materials[0], materials[0], materials[1], materials[0], materials[0], materials[0]],
    );
    mesh.name = "coin_front_mid";
    mesh.position.set(-1.5, 0.5, 3);
    const pivot = new THREE.Group();
    pivot.name = "coin_front_mid_pivot";
    pivot.position.set(0, 0, 0);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 1, 3),
      [materials[2], materials[0], materials[1], materials[0], materials[0], materials[0]],
    );
    mesh.name = "coin_front_right";
    mesh.position.set(2, 0.5, 3);
    const pivot = new THREE.Group();
    pivot.name = "coin_front_right_pivot";
    pivot.position.set(0, 0, 0);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 1, 3),
      [materials[1], materials[1], materials[1], materials[2], materials[1], materials[1]],
    );
    mesh.name = "coin_stack_top";
    mesh.position.set(-0.5, 1.5, 0.5);
    const pivot = new THREE.Group();
    pivot.name = "coin_stack_top_pivot";
    pivot.position.set(0, 0, 0);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  root.userData.img2blockbench = {
    representation: "minecraft-cuboids",
    componentCount: 7,
    source: "agent-authored-image-reconstruction",
  };
  return root;
}
