import * as THREE from "three";

/**
 * Generated by img2blockbench from its Minecraft cuboid scene spec.
 * Edit the JSON specification, not this generated file.
 */
export function createGoldBarModel(): THREE.Group {
  const root = new THREE.Group();
  root.name = "gold_bar";
  const materials = [
    new THREE.MeshBasicMaterial({ name: "gold_bright", color: "#ffd840", toneMapped: false }),
    new THREE.MeshBasicMaterial({ name: "gold_polished", color: "#e8b020", toneMapped: false }),
    new THREE.MeshBasicMaterial({ name: "gold_shade", color: "#c88810", toneMapped: false }),
    new THREE.MeshBasicMaterial({ name: "stamp_dark", color: "#8a6000", toneMapped: false }),
  ];

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(16, 2, 5),
      [materials[2], materials[2], materials[1], materials[2], materials[0], materials[2]],
    );
    mesh.name = "bar_base";
    mesh.position.set(0, 1, 0);
    const pivot = new THREE.Group();
    pivot.name = "bar_base_pivot";
    pivot.position.set(0, 0, 0);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(15, 1, 4),
      [materials[1], materials[1], materials[1], materials[1], materials[0], materials[2]],
    );
    mesh.name = "bar_mid";
    mesh.position.set(0, 2.5, 0);
    const pivot = new THREE.Group();
    pivot.name = "bar_mid_pivot";
    pivot.position.set(0, 0, 0);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(14, 2, 3),
      [materials[0], materials[0], materials[0], materials[1], materials[0], materials[2]],
    );
    mesh.name = "bar_top";
    mesh.position.set(0, 4, 0);
    const pivot = new THREE.Group();
    pivot.name = "bar_top_pivot";
    pivot.position.set(0, 0, 0);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  root.userData.img2blockbench = {
    representation: "minecraft-cuboids",
    componentCount: 3,
    source: "agent-authored-image-reconstruction",
  };
  return root;
}
